### ISSUE TITLE
请问怎么添加新的水印模板

### ISSUE THREAD

**Issue by qiushi9** [yl305237731/yolo_v1-pytorch#2]
这个项目非常棒，谢谢你的分享，这正是我现在想要解决的问题。
我想问的是：如果我想让它能够识别更多不同的水印，应该怎么弄？
希望得到你的回复！！谢谢！

**Comment by yl305237731** [comment]
水印模板是自己用ps扣的，带 alpha 透明通道的png图像，用PIL Image.composite 进行合成, 水印随机调整尺度、亮度打到图片任意位置。

**Comment by yl305237731** [comment]
水印模板是自己用ps扣的，带 alpha 透明通道的png图像，用PIL Image.composite 进行合成, 水印随机调整尺度、亮度打到图片任意位置。 @qiushi9
